from .repo_abstract import RepoAbstract


class ETF(RepoAbstract):

    def __init__(self):
        self.stocks = {
            'AAXJ': "iShares MSCI All Country Asia ex Japan Index Fund ",
            'ACWI': "iShares MSCI ACWI Index Fund ",
            'ACWV': "iShares MSCI All Country World Minimum Volatility ETF ",
            'ACWX': "iShares MSCI ACWI ex US Index Fund ",
            'AFTY': "CSOP FTSE China A50 ETF",
            'AGG': "iShares Core Total US Bond Market ETF ",
            'AGQ': "ProShares Ultra Silver ETF",
            'AIA': "iShares Asia 50 ETF",
            'ALFA': "AlphaClone Alternative Alpha ETF ",
            'AMJ': "The JPMorgan Alerian MLP Index ETN ",
            'AMLP': "Alerian MLP ETF ",
            'ANGL': "VanEck Vectors Fallen Angel High Yield Bond ETF",
            'ARKK': "ARK Innovation ETF",
            'ARGT': "Global X FTSE Argentina 20 ETF ",
            'ASHR': "db X-trackers Harvest CSI 300 China A-Shares Fund ",
            'ASHS': "Deutsche X-trackers Harvest CSI 500 China A-Shares Small Cap ETF ",
            'BAL': "iPath Dow Jones-UBS Cotton Subindex Total Return ETN ",
            'BBH': "VanEck Vectors Biotech ETF ",
            'BFOR': "Barron's 400 ETF ",
            'BIB': "ProShares Ultra Nasdaq Biotechnology ETF",
            'BIL': "SPDR Bloomberg Barclays 1-3 Month T-Bill ETF",
            'BIS': "ProShares UltraShort Nasdaq Biotechnology ETF ",
            'BJK': "VanEck Vectors Gaming ETF ",
            'BKLN': "Senior Loan Portfolio ",
            'BND': "Vanguard Total Bond Market ETF ",
            'BNDX': "Vanguard Total International Bond ETF ",
            'BNO': "United States Brent Oil Fund LP ETF ",
            'BOIL': "ProShares Ultra DJ-UBS Natural Gas ETF ",
            'BOND': "Pimco Total Return ETF ",
            'BOTZ': "Global X Robotics & Artificial Intelligence ETF",
            'BRF': "VanEck Vectors Brazil Small Cap ETF ",
            'BRZU': "Direxion Daily Brazil Bull 3X Shares ETF",
            'BSV': "Vanguard Short-Term Bond ETF",
            'BWX': "SPDR Bloomberg Barclays International",
            'BZF': "WisdomTree Dreyfus Brazilian Real Fund ",
            'BZQ': "ProShares UltraShort MSCI Brazil ETF",
            'CANE': "Teucrium Sugar Fund",
            'CEMB': "iShares®® JP Morgan EM Corporate Bond ETF",
            'CEW': "WisdomTree Dreyfus Emerging Currency Fund ",
            'CFA': "VictoryShares US 500 Volatility Wtd ETF",
            'CHAD': "Direxion Daily CSI 300 China A Share Bear 1X Shares ETF",
            'CHAU': "Direxion Daily CSI 300 China A Share Bull 2X Shares ETF",
            'CHIQ': "Global X China Consumer ETF ",
            'CHIX': "Global X China Financials ETF ",
            'CIBR': "First Trust NASDAQ CEA Cybersecurity ETF ",
            'CNXT': "VanEck Vectors China AMC SME-ChiNext ETF ",
            'CNYA': "iShares®® MSCI China A ETF",
            'CORN': "Teucrium Corn Fund ",
            'COW': "iPath Dow Jones-UBS Livestock Total Return Sub-Index ETN ",
            'COWZ': "Pacer US Cash Cows 100 ETF",
            'CROC': "ProShares UltraShort Australian Dollar ETF ",
            'CSD': "Invesco Spin-Off ETF ",
            'CURE': "Direxion Daily Healthcare Bull 3x Shares ",
            'CVY': "Invesco Multi-Asset Income ETF ",
            'CWB': "SPDR Barclays Convertible Securities ETF ",
            'CWI': "SPDR MSCI ACWI (ex-US) ETF ",
            'CYB': "WidsomTree Dreyfus China Yuan Fund ",
            'DBA': "Invesco DB Agriculture Fund ",
            'DBB': "Invesco DB Base Metals Fund",
            'DBC': "Invesco DB Commodity Index Tracking Fund ",
            'DBEF': "db X-trackers MSCI EAFE Hedged Equity Fund ",
            'DBEU': "Deutsche X-trackers MSCI Europe Hedged Equity ETF ",
            'DBJP': "db X-trackers MSCI Japan Hedged Equity Fund ",
            'DBO': "Invesco DB Oil Fund",
            'DBS': "Invesco DB Silver Fund ",
            'DBV': "Invesco DB G10 Currency Harvest Fund ",
            'DDG': "ProShares Short Oil & Gas ETF ",
            'DDM': "Ultra Dow 30 ProShares ETF",
            'DEM': "WisdomTree Emerging Markets Equity, Income Fund ",
            'DFE': "WisdomTree Europe SmallCap Dividend Fund ",
            'DFEN': "Direxion Daily Aerospace & Defense Bull 3X Shares",
            'DFJ': "WisdomTree Japan SmallCap Dividend Fund ",
            'DGRW': "WisdomTree U.S. Dividend Growth Fund ",
            'DGS': "WisdomTree Emerging Markets SmallCap Dividend Fund   ",
            'DIA': "SPDR Dow Jones Industrial Average ETF ",
            'DIG': "Ultra Oil & Gas ProShares ETF",
            'DJP': "iPath Dow Jones-UBS Commodity Index Total Return ETN",
            'DLN': "WisdomTree LargeCap Dividend Fund ",
            'DLS': "WisdomTree International SmallCap Dividend Fund ",
            'DON': "WisdomTree MidCap Dividend Fund ",
            'DRIP': "Direxion Daily S&P Oil & Gas Exp. & Prod. Bear 3X Shares ETF",
            'DRN': "Direxion Daily Real Estate Bull 3x Shares ETF",
            'DRV': "Direxion Daily Real Estate Bear 3x Shares ETF",
            'DTEC': "ALPS Disruptive Technologies ETF ",
            'DTN': "WisdomTree Dividend ex-Financials Fund ",
            'DUG': "UltraShort Oil & Gas ProShares ETF",
            'DUST': "Direxion Daily Gold Miners Bear 3x Shares ETF",
            'DVY': "iShares DJ Select Dividend ETF",
            'DWAS': "Invesco DWA SmallCap Technical Leaders Portfolio ",
            'DWX': "SPDR S&P International Dividend ETF ",
            'DXD': "UltraShort Dow 30 ProShares ETF",
            'DXJ': "WisdomTree Japan Hedged Equity Fund ",
            'DXJS': "WisdomTree Japan Hedged Small Cap Fund ",
            'EBND': "SPDR Barclays Emerging Markets Local Bond ETF ",
            'ECH': "iShares MSCI Chile Investable Market Index Fund ",
            'ECNS': "iShares MSCI China Small-Cap ETF ",
            'ECON': "EGShares Emerging Markets Consumer ETF ",
            'EDC': "Direxionshares Emerging Markets Bull 3X Shares ETF",
            'EDIV': "SPDR S&P Emerging Markets Dividend ETF ",
            'EDZ': "Direxionshares Emerging Markets Bear 3X Shares ETF",
            'EEM': "iShares MSCI Emerging Markets Index ETF",
            'EEMV': "iShares MSCI Emerging Markets Minimum Volatility Index Fund ",
            'EET': "ProShares Ultra MSCI Emerging Markets ETF",
            'EEV': "UltraShort MSCI Emerging Markets ProShares ETF",
            'EFA': "Options on iShares MSCI EAFE Exchange Traded Fund ",
            'EFAV': "iShares MSCI EAFE Minimum Volatility Index Fund ",
            'EFG': "iShares MSCI EAFE Growth ETF ",
            'EFV': "iShares MSCI EAFE Value ETF ",
            'ELD': "WisdomTree Emerging Markets Local Debt Fund ",
            'EMLC': "VanEck Vectors Emerging Markets Local Currency Bond ETF",
            'EMB': "iShares JPMorgan USD Emerging Markets Bond Fund ",
            'ENZL': "iShares MSCI New Zealand Capped ETF ",
            'EPI': "WisdomTree India Earnings Fund ",
            'EPV': "ProShares UltraShort MSCI Europe ETF",
            'ERX': "Direxionshares Energy Bull 3X Shares ETF",
            'EUFN': "iShares MSCI Europe Financials ETF ",
            'EUM': "Short MSCI Emerging Markets ProShares ETF",
            'EUO': "ProShares UltraShort Euro ETF",
            'EURL': "Direxion Daily FTSE Europe Bull 3x Shares ETF",
            'EWA': "iShares MSCI Australia Index Fund ",
            'EWC': "iShares MSCI Canada Index Fund ",
            'EWD': "iShares MSCI Sweden Index ETF",
            'EWG': "iShares MSCI Germany Index ETF",
            'EWH': "iShares MSCI Hong Kong Index ETF",
            'EWI': "iShares MSCI Italy Index Fund ",
            'EWJ': "iShares MSCI Japan Index ETF",
            'EWK': "iShares MSCI Belgium Capped ETF ",
            'EWL': "iShares MSCI Switzerland Index Fund ",
            'EWM': "iShares MSCI Malaysia Index Fund ",
            'EWN': "iShares MSCI Netherlands ETF ",
            'EWP': "iShares MSCI Spain Index ",
            'EWQ': "iShares MSCI France Index Fund ",
            'EWS': "iShares MSCI Singapore Index Fund ",
            'EWT': "iShares MSCI Taiwan Index Fund ",
            'EWU': "iShares MSCI United Kingdom ETF ",
            'EWV': "ProShares UltraShort MSCI Japan ETF",
            'EWW': "iShares MSCI Mexico Index ",
            'EWX': "SPDR S&P Emerging Small Cap ETF ",
            'EWY': "iShares iShares MSCI South Korea Index Fund ",
            'EWZ': "iShares MSCI Brazil Index Fund ",
            'EZA': "iShares MSCI South Africa Index ETF",
            'EZJ': "ProShares Ultra MSCI Japan ETF",
            'EZU': "iShares MSCI EMU Index Fund ",
            'FAS': "Direxionshares Financial Bull 3X Shares ETF",
            'FBT': "First Trust NYSE Biotechnology Index Fund ",
            'FAZ': "Direxionshares Financial Bear 3X Shares ETF",
            'FCA': "First Trust China AlphaDEX Fund ",
            'FCG': "First Trust ISE-Revere Natural Gas Index Fund ",
            'FDN': "First Trust Dow Jones Internet Index Fund ",
            'FEM': "First Trust Emerging Markets AlphaDEX Fund ",
            'FENY': "Fidelity MSCI Energy Index ETF ",
            'FEP': "First Trust Europe AlphaDEX Fund ",
            'FEX': "First Trust Large Cap Core AlphaDEX Fund ",
            'FEZ': "SPDR Euro Stoxx 50 ETF ",
            'FHLC': "Fidelity MSCI Health Care Index ETF ",
            'FM': "iShares MSCI Frontier 100 ETF ",
            'FMAT': "Fidelity MSCI Materials Index ETF ",
            'FNCL': "Fidelity MSCI Financials Index ETF ",
            'FNDE': "Schwab Fundamental Emerging Markets Large Company Index ETF ",
            'FNDF': "Schwab Fundamental International Large Company Index ETF ",
            'FNDX': "Schwab Fundamental U.S. Large Company Index ETF ",
            'FRAK': "VanEck Vectors Unconventional Oil & Gas ETF ",
            'FTAG': "First Trust Indxx Global Agriculture ETF ",
            'FTC': "First Trust Large Cap Growth AlphaDEX Fund ",
            'FTEC': "Fidelity MSCI Information Technology Index ETF ",
            'FV': "First Trust Dorsey Wright Focus 5 ETF ",
            'FVD': "First Trust Value Line Dividend Index Fund ",
            'FXA': "CurrencyShares Australian Dollar Trust ETF",
            'FXB': "CurrencyShares British Pound Sterling Trust ",
            'FXD': "First Trust Consumer Discretionary AlphaDEX Fund ",
            'FXE': "CurrencyShares Euro Trust ",
            'FXF': "CurrencyShares Swiss Franc Trust ",
            'FXG': "First Trust Consumer Staples AlphaDEX Fund ",
            'FXH': "First Trust Health Care AlphaDEX Fund ",
            'FXI': "iShares FTSA/Xinhua China 25 ETF",
            'FXL': "First Trust Technology AlphaDEX Fund ",
            'FXN': "First Trust Energy AlphaDEX Fund ",
            'FXP': "UltraShort FTSE/Xinhua China 25 ProShares ETF",
            'FXR': "First Trust Industrials/Producer Durables AlphaDEX Fund ",
            'FXU': "First Trust Utilities AlphaDEX Fund ",
            'GDX': "VanEck Vectors TR Gold Miners Index ETF",
            'GEM': "Goldman Sachs ActiveBeta Emerging Markets Equity ETF ",
            'GLD': "Options on SPDR Gold Shares ETF",
            'GLL': "ProShares UltraShort Gold ETF",
            'GMF': "SPDR S&P Emerging Asia Pacific ETF ",
            'GNR': "SPDR S&P Global Natural Resources ETF ",
            'GREK': "Global X FTSE Greece 20 ETF ",
            'GSG': "iShares GSCI Commodity-Indexed Trust ",
            'GSIE': "Goldman Sachs ActiveBeta International Equity ETF ",
            'GSLC': "Goldman Sachs ActiveBeta U.S. Large Cap Equity ETF ",
            'GUNR': "FlexShares Morningstar Global Upstream Natural Resources Index Fund  ",
            'GURU': "Global X Guru Index ETF ",
            'GUSH': "Direxion Daily S&P Oil & Gas Exp. & Prod. Bull 3X Shares ETF ",
            'GVI': "iShares Intermediate Government/Credit Bond ETF ",
            'GWX': "SPDR S&P International Small Cap ETF ",
            'GXC': "SPDR S&P China ETF ",
            'GXG': "Global X FTSE Colombia 20 ETF ",
            'HACK': "PureFunds ISE Cyber Security ETF ",
            'HDGE': "Active Bear ETF",
            'HDV': "iShares High Dividend Equity Fund ",
            'HEFA': "iShares Currency Hedged MSCI EAFE ETF ",
            'HEDJ': "WisdomTree Europe Hedged Equity Fund ",
            'HEWG': "iShares Currency Hedged MSCI Germany ETF ",
            'HEWJ': "iShares Currency Hedged MSCI Japan ETF ",
            'HEZU': "iShares Trust - iShares Currency Hedged MSCI EMU ETF ",
            'HYD': "VanEck Vectors High Yield Municipal Index ETF ",
            'HYG': "iShares iBoxx $ High Yield Corporate Bond Fund ",
            'HYLD': "Peritus High Yield ETF ",
            'HYMB': "SPDR Nuveen S&P High Yield Municipal Bond ETF ",
            'HYS': "PIMCO 0-5 Year High Yield Corporate Bond Index Fund ",
            'IAI': "iShares Dow Jones US Broker-Dealers Index Fund ",
            'IAU': "iShares COMEX Gold Trust ",
            'IBB': "iShares Nasdaq Biotechnology ETF",
            'ICF': "iShares Cohen & Steers Realty Majors Index Fund ",
            'IDU': "iShares DJ US Utilities Sector ETF",
            'IDV': "iShares Dow Jones International Select Dividend Index Fund ",
            'IEF': "iShares Lehman 7-10 Year Treasury Bond Fund ",
            'IEFA': "iShares Core MSCI EAFE ETF ",
            'IEI': "iShares Barclays 3-7 Year Treasury Bond Fund ",
            'IEMG': "iShares Core MSCI Emerging Markets ETF ",
            'IEO': "iShares Dow Jones US Oil & Gas Exploration & Production Index Fund ",
            'IEV': "iShares S&P Europe 350 Index Fund ",
            'IEZ': "iShares Dow Jones US Oil Equipment & Services Index Fund ",
            'IFGL': "iShares FTSE EPRA/NAREIT Developed Real Estate ex-US Index Fund ",
            'IGF': "iShares Global Infrastructure ETF ",
            'IGN': "iShares North American Tech-Multimedia Networking ETF ",
            'IGOV': "iShares International Treasury Bond ETF ",
            'IGV': "iShares S&P North American Technology-Software Index Fund ",
            'IHDG': "WisdomTree International Hedged Dividend Growth Fund ",
            'IHE': "iShares U.S. Pharmaceuticals ETF ",
            'IHF': "iShares Dow Jones US Healthcare Providers Index ",
            'IHI': "iShares U.S. Medical Devices ETF ",
            'IHY': "VanEck Vectors International High Yield Bond ETF ",
            'IJH': "iShares S&P MidCap 400 Index Fund ",
            'IJJ': "iShares S&P MidCap 400 Value Index Fund ",
            'IJK': "iShares S&P MidCap 400 Growth Index Fund ",
            'IJR': "iShares S&P 600 Index Fund ",
            'IJS': "iShares S&P SmallCap 600 Value Index Fund ",
            'IJT': "iShares S&P SmallCap 600 Growth Index Fund ",
            'ILF': "iShares S&P Latin America 40 Index ",
            'INDA': "iShares MSCI India ETF ",
            'IOO': "iShares S&P Global 100 Index Fund ",
            'IPFF': "iShares International Preferred Stock ETF ",
            'ISRA': "VanEck Vectors Israel ETF ",
            'ITB': "iShares Dow Jones US Home Construction ETF",
            'ITOT': "iShares Core S&P Total US Stock Market ETF ",
            'IVE': "iShares S&P 500 Value ETF ",
            'IVV': "iShares S&P 500 Index Fund ",
            'IVW': "iShares S&P 500 Growth Index Fund ",
            'IWB': "iShares Russell 1000 Index Fund ",
            'IWC': "iShares Russell Microcap Index Fund ",
            'IWD': "iShares Russell 1000 Value Index Fund ",
            'IWF': "iShares Russell 1000 Growth Index Fund ",
            'IWM': "iShares Russell 2000® Index Fund",
            'IWN': "iShares Russell 2000 Value Index Fund ",
            'IWO': "iShares Russell 2000 Growth Index Fund ",
            'IWP': "iShares Russell Midcap Growth Index Fund ",
            'IWR': "iShares Russell Midcap Index Fund ",
            'IWS': "iShares Russell Mid-Cap Value ETF ",
            'IWV': "iShares Russell 3000 Index Fund ",
            'IXC': "iShares S&P Global Energy Sector Index Fund   ",
            'IXJ': "iShares Global Healthcare ETF ",
            'IXP': "iShares Global Telecom ETF   ",
            'IXUS': "iShares Core MSCI Total International Stock ETF   ",
            'IYE': "iShares Trust - DJ US Energy Sector Index Fund   ",
            'IYF': "iShares Dow Jones US Financial Sector Index Fund ",
            'IYH': "iShares Trust - DJ US Healthcare Sector Index Fund   ",
            'IYM': "iShares Dow Jones Basic Materials Sector Index Fund   ",
            'IYR': "iShares DJ U.S. Real Estate ETF",
            'IYT': "iShares Dow Jones U.S. Transportation Average Index Fund ",
            'IYW': "iShares Dow Jones US Technology Sector Index Fund ",
            'IYZ': "iShares DJ U.S. Telecommunications Sector Index Fund ",
            'JDST': "Direxion Daily Junior Gold Miners Index Bear 3X Shares ETF",
            'JETS': "US Global Jets ETF ",
            'JJC': "iPath Dow Jones-UBS Copper Total Return Sub-Index ETN ",
            'JJG': "iPath Dow Jones-UBS Grains Subindex Total Return ETN ",
            'JNK': "SPDR Barclays Capital High Yield Bond ETF ",
            'JNUG': "Direxion Daily Junior Gold Miners Index Bull 3X Shares ETF",
            'JO': "iPath Dow Jones-UBS Coffee Subindex Total Return Sub-IndexSM ETN ",
            'KBE': "KBW Bank ETF ",
            'KBWB': "Invesco KBW Bank Portfolio ETF",
            'KCE': "KBW Capital Markets ETF ",
            'KIE': "KBW Insurance ETF ",
            'KOLD': "ProShares UltraShort DJ-UBS Natural Gas ETF ",
            'KRE': "KBW Regional Banking ETF ",
            'KWEB': "KraneShares CSI China Internet ETF ",
            'LABD': "Direxion Daily S&P Biotech Bear 3X Shares ETF ",
            'LABU': "Direxion Daily S&P Biotech Bull 3X Shares ETF",
            'LBJ': "Direxion Daily Latin America Bull 3X Shares ETF",
            'LEMB': "iShares Emerging Markets Local ETF",
            'LQD': "iShares GS$ InvesTop Corporate Bond Fund ",
            'LTPZ': "PIMCO 15+ Year U.S. TIPS Index Exchange-Traded Fund ",
            'MBB': "iShares Barclays MBS Bond Fund ",
            'MCHI': "iShares MSCI China Index Fund ",
            'MDY': "Standard & Poor's MidCap 400 Index ETF",
            'MGC': "Vanguard Mega Cap 300 ETF ",
            'MGK': "Vanguard Mega Cap 300 Growth ETF ",
            'MGV': "Vanguard Mega Cap 300 Value ETF ",
            'MLPX': "Global X MLP & Energy Infrastructure ETF ",
            'MOAT': "VanEck Vectors Morningstar Wide Moat ETF ",
            'MOO': "VanEck Vectors Global Agribusiness ETF ",
            'MUB': "iShares S&P National AMT-Free Bond Fund ",
            'MUNI': "PIMCO Intermediate Municipal Bond Exchange-Traded Fund ",
            'MXI': "iShares Global Materials ETF ",
            'MYY': "ProShares Short MidCap 400 ETF",
            'MZZ': "UltraShort MidCap 400 ProShares ETF",
            'NIB': "iPath Dow Jones-UBS Cocoa Total Return Sub-IndexSM ETN ",
            'NOBL': "ProShares S&P 500 Aristocrats ETF ",
            'NUGT': "Direxion Daily Gold Miners Bull 2x Shares ETF",
            'OEF': "Options on iShares®® S&P 100® Index Fund ",
            'OIH': "VanEck Vectors Oil Services ETF ",
            'OUSA': "O'Shares FTSE US Quality Dividend ETF ",
            'PCEF': "Invesco CEF, Income Composite Portfolio ",
            'PCY': "Invesco Emerging Markets Sovereign Debt ETF ",
            'PDP': "Invesco DWA Momentum Portfolio ",
            'PEY': "Invesco High Yield Equity Dividend Achievers Portfolio ",
            'PFF': "iShares S&P U.S. Preferred Stock Index Fund ",
            'PGF': "Invesco Financial Preferred ETF ",
            'PGX': "Invesco Preferred ETF ",
            'PHB': "Invesco Fundamental High Yield Corporate Bond ETF ",
            'PICK': "iShares MSCI Global Select Metals & Mining Producers ETF ",
            'PID': "Invesco International Dividend Achievers Portfolio ",
            'PIE': "Invesco DWA Emerging Markets Technical Leaders ETF",
            'PIN': "Invesco India ETF ",
            'PIZ': "Invesco DWA Developed Markets Momentum ETF ",
            'PJP': "Invesco Dynamic Pharmaceuticals ETF ",
            'PKW': "Invesco Buyback Achievers ETF",
            'PNQI': "Invesco NASDAQ Internet ETF ",
            'PPH': "VanEck Vectors Pharmaceutical ETF ",
            'PRF': "Invesco FTSE RAFI US 1000 ETF ",
            'PSCH': "Invesco S&P SmallCap Health Care ETF ",
            'PSP': "Invesco Global Listed Private Equity ETF ",
            'PSQ': "Short QQQ ProShares ETF",
            'PST': "UltraShort Lehman 7-10 Treasury ProShares ETF ",
            'PXH': "Invesco FTSE RAFI Emerging Markets ETF",
            'PXJ': "Invesco Dynamic Oil & Gas Services ETF",
            'QID': "UltraShort QQQ ProShares ETF",
            'QLD': "Ultra QQQ ProShares ETF",
            'QQEW': "First Trust NASDAQ-100 Equal Weighted Index Fund ",
            'QQQ': "Invesco QQQ Trust",
            'QQQE': "Direxion NASDAQ-100 Equal Weighted Index Shares ",
            'QTEC': "First Trust NASDAQ-100 Technology Index Fund ",
            'REK': "ProShares Short Real Estate ETF",
            'REM': "iShares FTSE NAREIT Mortgage Plus Capped Index Fund ",
            'REMX': "VanEck Vectors Rare Earth/Strategic Metals ETF ",
            'RETL': "Direxion Daily Retail Bull 3X Shares ETF",
            'REW': "ProShares UltraShort Technology ETF",
            'REZ': "iShares Residential Real Estate Capped ETF ",
            'RING': "iShares MSCI Global Gold Miners ETF ",
            'RJA': "Agriculture Total Return ETF",
            'RJI': "Total Return ETF",
            'RJN': "Energy Total Return ETF ",
            'ROM': "ProShares Ultra Technology ",
            'RPV': "Invesco S&P 500 Pure Value ETF ",
            'RSP': "Invesco S&P 500 Equal Weight ETF ",
            'RSX': "VanEck Vectors Russia ETF ",
            'RTH': "VanEck Vectors Oil Services ETF ",
            'RUSL': "Direxion Daily Russia Bull 3x Shares ETF",
            'RWJ': "RevenueShares Small Cap Fund ",
            'RWK': "RevenueShares Mid Cap Fund ",
            'RWL': "RevenueShares Large Cap ETF ",
            'RWM': "ProShares Short Russell 2000 ETF",
            'RWO': "SPDR Dow Jones Global Real Estate ETF ",
            'RWR': "SPDR Dow Jones REIT ETF ",
            'RWX': "SPDR Dow Jones International Real Estate ETF ",
            'RXL': "ProShares Ultra Health Care ETF",
            'RYH': "Invesco S&P 500 Equal Weight Health Care ETF ",
            'SAA': "ProShares Ultra SmallCap 600 ",
            'SBIO': "ALPS Medical Breakthroughs ETF ",
            'SCHA': "Schwab U.S. Small-Cap ETF ",
            'SCHB': "Schwab U.S. Broad Market ETF ",
            'SCHC': "Schwab International Small-Cap Equity ETF ",
            'SCHD': "Schwab US Dividend Equity ETF ",
            'SCHE': "Schwab Emerging Markets Equity ETF ",
            'SCHF': "Schwab International Equity ETF ",
            'SCHG': "Schwab U.S. Large-Cap Growth ETF ",
            'SCHH': "Schwab U.S. REIT ETF ",
            'SCHM': "Schwab U.S. Mid-Cap ETF ",
            'SCHP': "Schwab U.S. TIPs ETF ",
            'SCHV': "Schwab U.S. Large-Cap Value ETF ",
            'SCHX': "Schwab U.S. Large-Cap ETF ",
            'SCJ': "iShares MSCI Japan Small-Cap ETF ",
            'SCO': "ProShares UltraShort DJ-AIG Crude Oil ETF",
            'SCZ': "iShares MSCI EAFE Small-Cap ETF ",
            'SDIV': "Global X SuperDividend ETF ",
            'SDOW': "ProShares UltraPro Short Dow30 ETF",
            'SDS': "UltraShort S&P 500 ProShares ETF",
            'SDY': "SPDR S&P Dividend ETF ",
            'SGG': "iPath Dow Jones-UBS Sugar Total Return Sub-IndexSM ETN ",
            'SGOL': "ETFS Gold Trust ",
            'SHY': "Lehman 1-3 Year Treasury Bond Fund ",
            'SIL': "Global X Silver Miners ETF ",
            'SIVR': "ETFS Silver Trust ",
            'SJB': "ProShares Short High Yield ETF",
            'SJNK': "SPDR Barclays Short Term High Yield Bond ETF ",
            'SKF': "UltraShort Financials ProShares ",
            'SKYY': "First Trust ISE Cloud Computing Index Fund ",
            'SLV': "iShares® Silver Trust ",
            'SMH': "VanEck Vectors Semiconductor ETF ",
            'SMN': "UltraShort Basic Materials ProShares ETF",
            'SOCL': "Global X Social Media Index ETF ",
            'SOXX': "iShares PHLX SOX Semiconductor Sector Index Fund ",
            'SOYB': "Teucrium Soybean Fund ",
            'SPHB': "Invesco S&P 500 High Beta ETF ",
            'SPLV': "Invesco S&P 500 Low Volatility ETF ",
            'SPXU': "ProShares UltraPro Short S&P 500 ETF",
            'SPY': "SPDR S&P 500 ETF Trust ",
            'SQQQ': "ProShares UltraPro Short QQQ ETF",
            'SRS': "UltraShort Real Estate ProShares ETF",
            'SSO': "Ultra S&P 500 ProShares ETF",
            'SVXY': "ProShares Short VIX Short-Term Futures ETF",
            'TAN': "Claymore/MAC Global Solar Energy Index ETF ",
            'TBF': "ProShares Short 20+Year Treasury ETF",
            'TBT': "UltraShort Lehman 20+Year Treasury ProShares ETF",
            'TDIV': "First Trust NASDAQ Technology Dividend Index Fund ",
            'TIP': "iShares Barclays US Treasury Inflation Protected Securities Fund ",
            'TLH': "iShares Barclays 10-20 Year Treasury Bond Fund ",
            'TLT': "iShares® Lehman 20+ Year Treasury Bond Fund ",
            'TMF': "Direxion Daily 30-Year Treasury Bull 3X ETF",
            'TMV': "Direxion Daily 30-Year Treasury Bear 3X ETF",
            'TNA': "Direxion Daily Small Cap Bull 3X Shares ETF",
            'TQQQ': "ProShares UltraPro QQQ ETF",
            'TTT': "ProShares UltraPro Short 20+ Year Treasury ETF",
            'TUR': "iShares MSCI Turkey ETF ",
            'TWM': "UltraShort Russell 2000 ProShares ETF",
            'TYD': "Direxion Daily 10-Year Treasury Bull 3X ETF",
            'TYO': "Direxion Daily 10-Year Treasury Bear 3X ETF",
            'TZA': "Direxionshares Small Cap Bear 3X Shares ETF",
            'UBT': "ProShares Ultra 20+ Year Treasury ETF",
            'UCO': "ProShares Ultra DJ-AIG Crude Oil ETF",
            'UDN': "Invesco DB US Dollar Index Bearish Fund ",
            'UGA': "United States Gasoline Fund ",
            'UGL': "ProShares Ultra Gold ETF",
            'UNG': "United States Natural Gas Fund ",
            'UNL': "United States 12 Month Natural Gas Fund LP ETF",
            'UPRO': "ProShares UltraPro S&P 500 ",
            'URA': "Global X Uranium ETF ",
            'USD': "Ultra Semiconductor ProShares ETF",
            'USDU': "WisdomTree Bloomberg U.S. Dollar Bullish Fund ",
            'USL': "United States 12 Month Oil Fund LP ETF",
            'USMV': "iShares MSCI USA Minimum Volatility Index Fund ",
            'USO': "United States Oil Fund ",
            'UST': "ProShares Ultra 7-10 Year Treasury ETF",
            'UUP': "Invesco DB US Dollar Index Bullish Fund ",
            'UVXY': "ProShares Ultra VIX Short-Term Futures ETF",
            'UWM': "Ultra Russell 2000® ProShares ETF",
            'UYG': "Ultra Financials ProShares ETF",
            'UYM': "Ultra Basic Materials ProShares ETF ",
            'VAW': "Vanguard Materials ETF ",
            'VB': "Vanguard Small-Cap ETF ",
            'VBK': "Vanguard Small-Cap Growth ETF ",
            'VBR': "Vanguard Small-Cap Value ETF ",
            'VCIT': "Vanguard Intermediate-Term Corporate Bond ETF ",
            'VCLT': "Vanguard Long-Term Corporate Bond ETF ",
            'VCR': "Vanguard Consumer Discretionary ETF ",
            'VDC': "Vanguard Consumer Staples ETF ",
            'VDE': "Vanguard Energy ETF ",
            'VEA': "Vanguard MSCI EAFE ETF ",
            'VEU': "Vanguard FTSE All-World ex-US ETF ",
            'VFH': "Vanguard Financials ETF ",
            'VGK': "Vanguard MSCI European ETF ",
            'VGT': "Vanguard Information Technology ETF ",
            'VHT': "Vanguard Health Care ETF ",
            'VIG': "Vanguard Dividend Appreciation ETF ",
            'VIXM': "ProShares VIX Mid-Term Futures ETF ",
            'VIS': "Vanguard Industrials ETF ",
            'VIXY': "Proshares VIX Short-Term Futures ETF ",
            'VNQI': "Vanguard Global ex-U.S. Real Estate ETF ",
            'VO': "Vanguard Mid-Cap ETF ",
            'VOE': "Vanguard Mid-Cap Value ETF ",
            'VOO': "Vanguard S&P 500 ETF ",
            'VOT': "Vanguard Mid-Cap Growth ETF ",
            'VOX': "Vanguard Telecommunication Services ETF ",
            'VPL': "Vanguard MSCI Pacific ETF ",
            'VPU': "Vanguard Utilities ETF ",
            'VRP': "Invesco Variable Rate Preferred ETF ",
            'VSS': "Vanguard FTSE All World ex-US Small-Cap ETF ",
            'VT': "Vanguard Total World Stock Index Fund ",
            'VTI': "Vanguard Total Stock Market ETF ",
            'VTV': "Vanguard Value ETF ",
            'VTWO': "Vanguard Russell 2000 ETF ",
            'VUG': "Vanguard Growth ETF ",
            'VV': "Vanguard Large-Cap ETF ",
            'VXF': "Vanguard Extended Market ETF ",
            'VXX': "iPath S&P 500 VIX Short-Term Futures Index ETN ",
            'VXZ': "iPath S&P 500 VIX Mid-Term Futures Index ETN ",
            'VYM': "Vanguard High Dividend Yield ETF ",
            'WEAT': "Tecrium Wheat Fund ",
            'WOOD': "iShares S&P Global Timber & Forestry Index Fund ",
            'XBI': "SPDR Biotech ETF ",
            'XES': "SPDR SPDR Oil & Gas Equipment & Services ETF ",
            'XHB': "SPDR Homebuilders ETF ",
            'XLB': "Materials Select Sector SPDR ",
            'XLE': "Energy Select Sector SPDR",
            'XLF': "Financial Select Sector SPDR ",
            'XLI': "Industrial Select Sector SPDR ",
            'XLK': "Technology Select Sector SPDR ",
            'XLP': "Consumer Staples Select Sector SPDR ",
            'XLU': "Utilities Select Sector SPDR ",
            'XLV': "Health Care Select Sector SPDR ",
            'XLY': "Consumer Discretionary Select Sector SPDR ",
            'XME': "SPDR S&P Metals & Mining ETF ",
            'XOP': "SPDR S&P Oil & Gas Exploration & Production ETF ",
            'XPH': "SPDR Pharmaceuticals ETF ",
            'XPP': "ProShares Ultra FTSE/Xinhua China 50 ETF",
            'XRT': "SPDR SPDR S&P Retail ETF ",
            'XSD': "SPDR Semiconductor ETF ",
            'YANG': "Direxion Daily China 3X Bear Shares ETF",
            'YCL': "ProShares Ultra Yen ETF",
            'YCS': "ProShares UltraShort Yen ETF",
            'YINN': "Direxion Daily China 3X Bull Shares ETF",
            'YXI': "ProShares Short FTSE China 50 ETF",
            'ZROZ': "PIMCO 25+ Year Zero Coupon U.S. Treasury Index Fund ",
            'ZSL': "ProShares UltraShort Silver ETF"
        }
